#!/usr/bin/env ruby
require File.join(File.dirname(__FILE__), 'lib', 'roulette.rb')

config_file = "config/roulette.yml"

unless File.exists? config_file
  ccputs "{red}config file does not exists:", "{yellow}#{config_file}"
  exit 1
end

require 'yaml'

ccputs "{green}Loading #{config_file}"
config = YAML::load_file config_file


